---
apiVersion: v1
kind: Namespace
metadata:
  name: openldap
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  type: NodePort
  ports:
    - port: 1389
      name: openldap
      targetPort: tcp-ldap
      nodePort: 32500
  selector:
    app.kubernetes.io/name: openldap
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: openldap
  namespace: openldap
data:
  openldap.ldif: |
    dn: dc=example,dc=org
    objectClass: dcObject
    objectClass: organization
    dc: example
    o: example

    dn: ou=users,dc=example,dc=org
    objectClass: organizationalUnit
    ou: users

    dn: cn=user01,ou=users,dc=example,dc=org
    cn: User1
    cn: user01
    sn: Bar1
    objectClass: inetOrgPerson
    objectClass: posixAccount
    objectClass: shadowAccount
    userPassword: password01
    uid: user01
    mail: user01@example.com
    uidNumber: 1000
    gidNumber: 1000
    homeDirectory: /home/user01

    dn: cn=user02,ou=users,dc=example,dc=org
    cn: User2
    cn: user02
    sn: Bar2
    objectClass: inetOrgPerson
    objectClass: posixAccount
    objectClass: shadowAccount
    userPassword: password02
    uid: user02
    mail: user02@example.com
    uidNumber: 1001
    gidNumber: 1001
    homeDirectory: /home/user02

    dn: cn=clusterusers,ou=users,dc=example,dc=org
    cn: clusterusers
    objectClass: groupOfNames
    member: cn=user01,ou=users,dc=example,dc=org
    member: cn=user02,ou=users,dc=example,dc=org
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: openldap
          image: docker.io/bitnami/openldap:latest
          imagePullPolicy: "Always"
          env:
            - name: LDAP_ADMIN_USERNAME
              value: "admin"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminpassword
                  name: openldap
          ports:
            - name: tcp-ldap
              containerPort: 1389
          volumeMounts:
          - name: config
            mountPath: /ldifs
      volumes:
      - name: config
        configMap:
          name: openldap
          items:
          - key: openldap.ldif
            path: openldap.ldif
