---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc-example-app
  labels:
    app: oidc-example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oidc-example-app
  template:
    metadata:
      labels:
        app: oidc-example-app
    spec:
      containers:
        - name: oidc-example-app
          image: quay.io/mvala/oidc-example-app:latest
          command: ["/usr/local/bin/oidc-example-app"]
          args:
            - "--issuer=$(ISSUER)"
            - "--issuer-root-ca=/etc/tls/root-ca/ca.pem"
            - "--listen=http://0.0.0.0:5555"
            - "--redirect-uri=http://oidc-example-app.{{MINIKUBE_IP}}.nip.io/callback"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "100m"

          ports:
            - containerPort: 5555

          env:
          - name: ISSUER
            value: https://dex.{{MINIKUBE_IP}}.nip.io:32000

          volumeMounts:
          - name: tls
            mountPath: /etc/tls/root-ca

      volumes:
      - name: tls
        secret:
          secretName: root-ca
---
kind: Service
apiVersion: v1
metadata:
  name: oidc-example-app
spec:
  selector:
    app: oidc-example-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5555
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: oidc-example-app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  rules:
    - host: oidc-example-app.{{MINIKUBE_IP}}.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oidc-example-app
                port:
                  number: 8080
