---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-gateway
  labels:
    app: che-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: che-gateway
  template:
    metadata:
      labels:
        app: che-gateway
    spec:
      serviceAccountName: che-gateway
      containers:
      - name: traefik-8080
        image: traefik:2.4.8
        volumeMounts:
        - name: traefik-config
          mountPath: /etc/traefik
        - name: traefik-dynamic-config
          mountPath: "/dynamic-config"

      - name: config-map-sync
        image: quay.io/che-incubator/configbump:latest
        env:
          - name: CONFIG_BUMP_DIR
            value: "/dynamic-config"
          - name: CONFIG_BUMP_LABELS
            value: "app=che,role=gateway-config"
          - name: CONFIG_BUMP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
        - name: traefik-dynamic-config
          mountPath: "/dynamic-config"

      - name: oauth2-proxy-4180
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.0.1
        command: ['oauth2-proxy']
        args:
        - "--config=/etc/oauth2-proxy/oauth2-proxy.cfg"
        - "--provider-ca-file=/etc/tls/root-ca/ca.pem"
        volumeMounts:
        - name: oauth2-proxy-config
          mountPath: /etc/oauth2-proxy
        - name: tls
          mountPath: /etc/tls/root-ca
        ports:
        - containerPort: 4180

      - name: kube-rbac-proxy-8089
        image: quay.io/brancz/kube-rbac-proxy:v0.8.0
        command: ["kube-rbac-proxy"]
        args:
        - "--insecure-listen-address=127.0.0.1:8089"
        - "--upstream=http://127.0.0.1:8090/bench"
        - "--logtostderr=true"
        - "--v=10"
        ports:
          - containerPort: 8089
        volumeMounts:
        - name: kube-rbac-proxy-config
          mountPath: /etc/kube-rbac-proxy

      - name: dummy-http-8090
        image: containous/whoami:v1.5.0
        command: ["/whoami"]
        args: ["--port", "8090"]

      volumes:
      - name: oauth2-proxy-config
        configMap:
          name: oauth2-proxy
      - name: tls
        secret:
          secretName: root-ca
      - name: traefik-config
        configMap:
          name: traefik-config
      - name: traefik-dynamic-config
        emptyDir: {}
      - name: kube-rbac-proxy-config
        configMap:
          name: kube-rbac-proxy-config
---
kind: Service
apiVersion: v1
metadata:
  name: che-gateway
spec:
  selector:
    app: che-gateway
  ports:
  - protocol: TCP
    port: 4180
    targetPort: 4180
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: che-gateway
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
      - che.{{MINIKUBE_IP}}.nip.io
    secretName: che-tls
  rules:
  - host: che.{{MINIKUBE_IP}}.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: che-gateway
            port: 
              number: 4180