---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: che-gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-configmaps
rules:
- verbs:
  - watch
  - get
  - list
  apiGroups:
  - ""
  resources:
  - configmaps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-config-maps-to-gateway-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-configmaps
subjects:
- kind: ServiceAccount
  name: che-gateway
