---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-gateway
  labels:
    app: che-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: che-gateway
  template:
    metadata:
      labels:
        app: che-gateway
    spec:
      serviceAccountName: che-gateway
      containers:
      - name: traefik-8080
        image: traefik:2.4.8
        volumeMounts:
        - name: traefik-config
          mountPath: /etc/traefik
        - name: traefik-dynamic-config
          mountPath: "/dynamic-config"

      - name: config-map-sync
        image: quay.io/che-incubator/configbump:latest
        env:
          - name: CONFIG_BUMP_DIR
            value: "/dynamic-config"
          - name: CONFIG_BUMP_LABELS
            value: "app=che,role=gateway-config"
          - name: CONFIG_BUMP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
        - name: traefik-dynamic-config
          mountPath: "/dynamic-config"

      - name: oauth2-proxy-4180
        image: quay.io/openshift/origin-oauth-proxy:4.7
        # command: ['oauth2-proxy']
        args:
        - "--config=/etc/oauth2-proxy/oauth2-proxy.cfg"
        volumeMounts:
        - name: oauth2-proxy-config
          mountPath: /etc/oauth2-proxy
        ports:
        - containerPort: 4180

      - name: header-rewrite-rpxy
        image: quay.io/mvala/header-rewrite-rpxy:latest
        command: ['/header-rewrite-rpxy']
        args: 
        - "--upstream=http://127.0.0.1:8080"
        - "--bind=127.0.0.1:8081"

      - name: kube-rbac-proxy-8089
        image: quay.io/openshift/origin-kube-rbac-proxy:4.7
        args:
        - "--insecure-listen-address=127.0.0.1:8089"
        - "--upstream=http://127.0.0.1:8090/bench"
        - "--logtostderr=true"
        - "--v=10"
        ports:
          - containerPort: 8089

      - name: dummy-http-8090
        image: containous/whoami:v1.5.0
        command: ["/whoami"]
        args: ["--port", "8090"]

      volumes:
      - name: oauth2-proxy-config
        configMap:
          name: oauth2-proxy
      - name: traefik-config
        configMap:
          name: traefik-config
      - name: traefik-dynamic-config
        emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: che-gateway
spec:
  selector:
    app: che-gateway
  ports:
  - protocol: TCP
    port: 4180
    targetPort: 4180
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: che-gateway
spec:
  host: che.{{HOSTNAME}}
  port:
    targetPort: 4180
  to:
    kind: Service
    name: che-gateway
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
